---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: $(CERTIFICATE_NAMESPACE)/$(CERTIFICATE_NAME)
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate
  failurePolicy: Fail
  name: mmemcahed.kb.io
  rules:
  - apiGroups:
    - cache.example.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - memcacheds
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: $(CERTIFICATE_NAMESPACE)/$(CERTIFICATE_NAME)
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate
  failurePolicy: Fail
  name: vmemcached.kb.io
  rules:
  - apiGroups:
    - cache.example.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - memcacheds
  sideEffects: None